In [ ]:
# correct the docstrings

def calculate(value1,value2):
''calculates the sum of two numbers and multiplies the sum by its product''
  return (value1+value2)*value1*value2

In [ ]:
# convert list of ids to primary keys
#Primary keys are unique values

list1 =[1,1,2,34,2,1,3,5,6,8,9]

In [ ]:
# whats wrong with the print output
Gender = 'Male'
Age = '33.133'
DOB = '23/04/1998.45'
store_str = 'I am a {} YO {} and my date of bith is {}'.format(DOB,Age,Gender)
print(store_str)

I am a 23/04/1998.45 YO 33.133 and my date of bith is Male

In [ ]:
# Write a Python program to create a list by concatenating a given list which range goes from 1 to n
# example list ['a','b']
# n = 5
# output ['a1','a2','a3','a4','a5','b1','b2','b3','b4','b5']

In [ ]:
#Whats wrong with the syntax
def number_info(value):
  if value == 2:
    return 'Value is 2'
  elif value%2==0:
    return 'Value is prime'
  elif value<5:
    return 'Value is less than 5'

In [ ]:
#Write a function to return every nth element from the list and store it in a single list as a list with nested list each containing n elements
# example:
# [1,2,3,4,5,6,7,8,8,9]
# n=3
# output:
# [[1,2,3],[4,5,6],[7,8,8],[9]]

import numpy as np

arr = np.random.randint(0,100,10000)